apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: denyall
spec:
  crd:
    spec:
      names:
        kind: DenyAll
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package kubernetes.denyall

        violation[{"msg": msg}] {
          msg := sprintf("REVIEW OBJECT: %v", [input.review])
        }
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: DenyAll
metadata:
  name: deny-all
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["*"]